Correct the patches for HDF4 patches
AnacondaRecipes/hdf4-feedstock pull request #2
Opened 2021-05-21 21:24 UTC by varlackc

This pull request fixes issues building the HDF4 package on graviton.

2021-05-21 21:42 UTC, pseudoyim commented
@varlackc - can you please provide details on where the patches you added come from? (e.g. from conda-forge?) Thank you.

2021-05-21 22:23 UTC, chenghlee approved these changes
Echoing @pseudoyim's comments. We need to know where these patches came from and why that source was chosen. Other issues to address:
1. Is there an upstream release that actually works on AARCH64, or is this all (effectively) custom software development?
2. The patches need to be stripped down to cover just AARCH64. Currently, they seem to pull in all sorts of architectures (HPPA, M68K, etc.) that makes wrapping our heads around what the patches actually do very difficult.

2021-05-21 22:23 UTC, chenghlee requested changes
Echoing @pseudoyim's comments. We need to know where these patches came from and why that source was chosen. Other issues to address:

Is there an upstream release that actually works on AARCH64, or is this all (effectively) custom software development?
The patches need to be stripped down to cover just AARCH64. Currently, they seem to pull in all sorts of architectures (HPPA, M68K, etc.) that makes wrapping our heads around what the patches actually do very difficult.

2021-05-24 03:03 UTC, varlackc commented
The patches came from Conda-Forge the link is provided below: 
https://github.com/conda-forge/hdf4-feedstock/tree/master/recipe/patches

The patches were selected because there were several types issues that were already solved with the conda-forge patches.

2021-05-24 21:14 UTC, chenghlee commented on recipe/meta.yaml
> +        # - patches/debian/hdfi.h.patch
Why do we have multiple copies of these patches? If we are going to adopt the conda-forge packaging & patches, we should be following the names within their recipe.

2021-11-18 18:17 UTC, closed without merging